### PR TITLE
Genericize simple deploys

### PR DESCRIPTION
**Pull request by binary1230**
make a non-magfest specific version of the super-simple deploy.

with one-click now anyone can deploy the RAMS demo/generic event named CoolCon 9000

### CODE REVIEW

**Comment by thaeli** [comment]
Can we apply this to the docker build? Since we are trying to move towards that for upstream..

**Comment by EliAndrewC** [comment]
+1

**Comment by binary1230** [comment]
sure, that would be a good idea though I don't quite have the time right this second to do it personally.   this was mainly to see if I could get someone else up and running super-quick

**Comment by binary1230** [comment]
oh damnit, i just realized i merged this back into the upstream branch which is not what I wanted to do.....

**Comment by earl7399** [comment]
REVERT, REVERT, REVERT

## 

Robert Earl r.a.earl@gmail.com
FAX: 1-440-919-5086

**Pull request merged**
