### PR TITLE
fix magstock 6 initial deploy

### PR DESCRIPTION
**Pull request by binary1230**
Switches this to deploy magstock instead of prime.  merge after https://github.com/magfest/production-config/pull/1

Future things we can do to make this more flexible:
1) pass this as an env var from the host OS so it's not hardcoded and people can deploy multiple events in different dirs without editing the file
2) maintain separate branches for different event deploys in this repo.  branch names: magstock, classic, prime, etc.  any common changes go into master and get merged.  we don't expect this repo to really change that much so it's probably not a bad idea.

### CODE REVIEW

**Comment by binary1230** [comment]
don't merge until https://github.com/magfest/production-config/pull/1 is in to avoid breaking the deploy.

**Comment by binary1230** [comment]
this is ready for merge

**Comment by EliAndrewC** [comment]
+1

It's probably okay (maybe even good?) if our interns switch to MAGStock as their dev environment.  Plus it's not hard to switch back to magprime.  I've done that back-and-forth a ton of times, and it's just moving directories around.

**Comment by binary1230** [comment]
Cool and my recommended approach is to have one copy of this repo for each event you are working on. Then you only have to vagrant up whichever one you are working on, and can easily flip between them without any manual work

**Pull request merged**
